#!/usr/bin/env python3
"""Generate the checks catalog and scaffold missing per-check doc pages.

Reads the check manifest JSON (from `oh-my-safety checks --json`) on stdin.
argv[1] = repo root, argv[2] = mode ("write" or "check").

- Always prints the generated docs/checks/README.md content to stdout.
- In "write" mode, scaffolds a stub page for any check that lacks one.
- In "check" mode, prints "MISSING: <path>" to stderr for missing pages and
  exits 3 if any are missing (so CI can gate on it).
"""
import json
import os
import sys

STUB = """# {name}

**Category:** {category} · **Default severity:** {severity} · **Platforms:** {platforms} · **Default interval:** {interval}s

> Stub scaffolded by `scripts/gen-docs.sh`. Fill in the sections below, then
> run `make docs` to refresh the catalog.

## What it protects you from

_TODO: the real-world threat this check defends against._

## How it works

_TODO: the exact commands/files it inspects._

## Pass / warn / critical criteria

_TODO._

## What's baselined

_TODO: what a first run records, and what a later change flags._

## Permissions

_TODO: Full Disk Access / other permissions, and how it degrades without them._

## Configuration

_TODO: the `config.yaml` keys under `checks.{category}.{underscore}`._

## False positives & how to handle them

_TODO: how to `oh-my-safety ignore {name} <id>` or `accept {name}`._

## Known limitations

_TODO._
"""


def main() -> int:
    root = sys.argv[1]
    mode = sys.argv[2] if len(sys.argv) > 2 else "write"
    checks = json.load(sys.stdin)

    lines = []
    lines.append("# Checks catalog")
    lines.append("")
    lines.append("_Generated by `scripts/gen-docs.sh` from each check's manifest — "
                 "do not edit by hand. Run `make docs` after adding or changing a check._")
    lines.append("")
    lines.append("Everything is enabled by default. Turn any check or whole category "
                 "on/off with `oh-my-safety enable|disable <name>`.")
    lines.append("")

    by_cat = {}
    for c in checks:
        by_cat.setdefault(c.get("category", "other"), []).append(c)

    missing = []
    order = ["privacy", "security"]
    cats = order + [c for c in sorted(by_cat) if c not in order]
    for cat in cats:
        items = by_cat.get(cat)
        if not items:
            continue
        lines.append(f"## {cat.capitalize()}")
        lines.append("")
        lines.append("| Check | Severity | Platforms | Interval | What it checks |")
        lines.append("|-------|----------|-----------|----------|----------------|")
        for c in sorted(items, key=lambda x: x["name"]):
            name = c["name"]
            doc = c.get("doc") or f"docs/checks/{cat}/{name}.md"
            rel = os.path.relpath(os.path.join(root, doc), os.path.join(root, "docs/checks"))
            interval = c.get("interval") or "-"
            lines.append("| [{name}]({rel}) | {sev} | {plat} | {iv} | {desc} |".format(
                name=name, rel=rel, sev=c.get("severity") or "warn",
                plat=c.get("platforms") or "all", iv=interval,
                desc=c.get("description") or ""))
            # doc page existence / scaffolding
            doc_abs = os.path.join(root, doc)
            if not os.path.exists(doc_abs):
                if mode == "write":
                    os.makedirs(os.path.dirname(doc_abs), exist_ok=True)
                    with open(doc_abs, "w") as f:
                        f.write(STUB.format(
                            name=name, category=cat,
                            severity=c.get("severity") or "warn",
                            platforms=c.get("platforms") or "all",
                            interval=interval,
                            underscore=name.replace("-", "_")))
                    print(f"scaffolded {doc}", file=sys.stderr)
                else:
                    missing.append(doc)
                    print(f"MISSING: {doc}", file=sys.stderr)
        lines.append("")

    sys.stdout.write("\n".join(lines) + "\n")
    return 3 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
